# Generated by Django 4.2.20 on 2025-04-29 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(db_column='business_id', primary_key=True, serialize=False)),
                ('business_name', models.CharField(db_column='business_name', max_length=100)),
                ('business_phone_number', models.CharField(db_column='business_phone_number', max_length=15, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Reapplied', 'Reapplied')], db_column='status', default='Pending', max_length=50)),
                ('citizenship_front', models.ImageField(blank=True, db_column='citizenship_front', null=True, upload_to='citizenship/')),
                ('citizenship_back', models.ImageField(blank=True, db_column='citizenship_back', null=True, upload_to='citizenship/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'cart',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('order_item_id', models.AutoField(db_column='order_item_id', primary_key=True, serialize=False)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.TextField(db_column='status')),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='full_name', max_length=100)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
                ('address_line1', models.CharField(db_column='address_line1', max_length=255)),
                ('address_line2', models.CharField(blank=True, db_column='address_line2', max_length=255, null=True)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='payment_id', primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_column='payment_date')),
                ('payment_method', models.CharField(db_column='payment_method', max_length=100)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=100)),
                ('product_img', models.ImageField(blank=True, db_column='product_img', null=True, upload_to='product_img/')),
                ('product_description', models.TextField(db_column='product_description', max_length=100)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'product_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(db_column='review_id', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='comment')),
                ('rating', models.IntegerField(db_column='rating', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('middle_name', models.CharField(blank=True, db_column='middle_name', max_length=100, null=True)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('email', models.CharField(db_column='email', unique=True)),
                ('password', models.CharField(db_column='password')),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('role', models.CharField(db_column='role', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(db_column='cart_item_id', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity', default=1)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('cart_id', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('product_id', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'db_table': 'cart_item',
                'unique_together': {('cart_id', 'product_id')},
            },
        ),
    ]
